backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/images" # Media files will be stored in the repo under assets/images
public_folder: "/assets/images" # The src attribute for uploaded media will begin with /assets/images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Description", name: "hero_description", widget: "text"}
          - {label: "About Title", name: "about_title", widget: "string"}
          - {label: "About Text", name: "about_text", widget: "markdown"}
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
